### ISSUE TITLE
Detect if it needs HedgeNeedle to open the model

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [AdelQue/FrontiersAnimDecompress#3]
instead of throwing an error

**Comment by AdelQue** [comment]
The model and skeleton importer included in the release is not part of this repository. The model and skeleton importer is pulled from [here](https://github.com/Turk645/Hedgehog-Engine-2-Mesh-Blender-Importer), and if you have any issues or suggestions for that plugin, you should open an issue in that repo. 

In this repo is the compression/decompression application, and the blender plugins for the animation importer, animation exporter, and skeleton exporter. Please only open issues or suggestions within the scope of these tools.
